import type { Metadata } from "next";
import Header from "@/components/home/Header";
import Sidebar from "@/components/home/Sidebar";

import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "@/contexts/UserProvider";
import { TransactionProvider } from "@/contexts/TransactionProvider";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Banking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <Toaster position="top-right" />
        <UserProvider>
          <TransactionProvider>
            <div className="h-screen flex flex-col">
              <Header />
              <div className="flex flex-1 overflow-hidden">
                <Sidebar />
                <main className="flex-1 overflow-auto bg-gray-50 md:p-6 p-2 scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-transparent hover:scrollbar-thumb-gray-400">
                  {children}
                </main>
              </div>
            </div>
          </TransactionProvider>
        </UserProvider>
      </body>
    </html>
  );
}
